version: 2.1
jobs:
  build:
   docker:
     - image: circleci/node
    steps:
      - run: yarn install
      - run: yarn test:unit
      - store_test_results:
          path: test-results
      - run: yarn build
